using Messaging.Common.Extensions;
using Messaging.Common.Options;
using NotificationService.Application.Messaging;
using NotificationService.Application.Services;
using NotificationService.Contracts.Interfaces;
using NotificationService.Contracts.Messaging;
using NotificationService.Infrastructure.BackgroundJobs;
using NotificationService.Infrastructure.Messaging;
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.Configure<RabbitMqOptions>(builder.Configuration.GetSection("RabbitMq"));
var mq = builder.Configuration.GetSection("RabbitMq").Get<RabbitMqOptions>()!;
builder.Services.AddRabbitMq(mq.HostName, mq.UserName, mq.Password, mq.VirtualHost);
builder.Services.AddScoped<IOrderPlacedHandler, OrderPlacedHandler>();
builder.Services.AddScoped<INotificationProcessor, NotificationProcessorService>();
builder.Services.AddHostedService<OrderPlacedConsumer>();
builder.Services.AddHostedService<NotificationWorker>();
var app = builder.Build();
app.UseSwagger();
app.UseSwaggerUI();
app.MapControllers();
app.Run();
